### ISSUE TITLE
Workflow for converting an existing R project into a package project

### ISSUE THREAD

**Issue by rachai** [jennybc/foofactors#1]
Hi, 

First of all: Thank you very much for this repo and the book. They are both extremely useful for a novice like myself!

Hopefully you are willing to answer a few questions. I created a new project in RStudio and hooked it up to a GitHub repo. The intent was to build a shiny app, but along the way I decided that it made more sense to make a package instead. That's when I discovered your book. 

Is there a preferred workflow to convert my existing shiny app project into a package project (with the devtools package or otherwise)? 

The main reason for asking is that my current file structure (which I don't mind changing) is not the same as that which was created when following along with chapter 2 of the book. 

Please forgive me if I have overlooked this in the book. 

Best regards,
Rishi

**Comment by jennybc** [comment]
FYI this repo is an example for the book, so not a great place to ask questions.

In general, the best place for such questions is RStudio's community site:

https://community.rstudio.com

That being said, I will answer:

`create_package()` can work with an existing directory, but it has no facilities for dealing with pre-existing files. Since you're using Git, I would make sure everything you have is committed and pushed and therefore, safe. Then I'd delete all the regular files in the project. Run `create_package()` on that directory. Then look at the git diffs. Any file you want to keep? Discard its changes (discard its deletion = keep it). Such files will probably also need to be relocated so they aren't in illegal places, in terms of what's allowed in an R package. It's possible I have some of the details wrong (I never do this). You'll just have to try and see what happens. Worst case, you just do a hard reset to the good, starting state.

It might also be easier to start a new package project and copy a few files over.

**Comment by rachai** [comment]
From now on I will post such questions on the Rstudio community site. Thank you very much for the swift response!
